### PR TITLE
Fixed bin

### LINKED ISSUE #664: CLI: v-change-domain-owner: Error: domain example.com doesn't exist
CLI: v-change-domain-owner always return
`Error: domain example.com doesn't exist`
Error in call v-search-domain-owner in https://github.com/serghey-rodin/vesta/blob/master/bin/v-change-domain-owner#L36 -
`owner=$(v-search-domain-owner $domain)`
instead of
`owner=$($BIN/v-search-domain-owner $domain)`

### PR DESCRIPTION
**Pull request by SysVoid**
Closes #664

### CODE REVIEW

**Comment by SysVoid** [comment]
Can someone check over this for me?

**Comment by dpeca** [comment]
To check if **v-change-domain-owner** always return ''_Error: domain example.com doesn't exist_'' ?

**Comment by SysVoid** [comment]
Yes, @dpeca.

**Comment by dpeca** [comment]
No error on Debian 8.5

root@debian:~# v-change-domain-owner peca.com peca
root@debian:~#

v16 is installed on this virtual machine... I didn't updated it via github.

Btw, today I noticed errors with $BIN when you run v-* commands in the same SSH session where you JUST INSTALLED Vesta.
If you just close that SSH session - and make new one - errors with $BIN disappear :)

**Comment by SysVoid** [comment]
Weird. Open that as another issue.

**Comment by dpeca** [comment]
I must check it first, I didn't discovered that, but one guy that tried to install my script for SSL.

/usr/local/vesta/bin/v-get-web-domain-value: line 21: /func/main.sh: No such file or directory
/usr/local/vesta/bin/v-get-web-domain-value: line 22: /func/domain.sh: No such file or directory
/usr/local/vesta/bin/v-get-web-domain-value: line 23: /conf/vesta.conf: No such file or directory
/usr/local/vesta/bin/v-get-web-domain-value: line 30: check_args: command not found
/usr/local/vesta/bin/v-get-web-domain-value: line 31: is_format_valid: command not found
/usr/local/vesta/bin/v-get-web-domain-value: line 32: is_object_valid: command not found
/usr/local/vesta/bin/v-get-web-domain-value: line 33: is_object_unsuspended: command not found
/usr/local/vesta/bin/v-get-web-domain-value: line 34: is_object_valid: command not found
/usr/local/vesta/bin/v-get-web-domain-value: line 41: get_domain_values: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 21: /func/main.sh: No such file or directory
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 22: /func/domain.sh: No such file or directory
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 23: /conf/vesta.conf: No such file or directory
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 30: check_args: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 31: is_format_valid: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 32: is_system_enabled: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 33: is_object_valid: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 34: is_object_unsuspended: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 35: is_object_valid: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 36: is_object_unsuspended: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 37: is_object_value_exist: command not found
/usr/local/vesta/bin/v-change-web-domain-sslcert: line 38: is_web_domain_cert_valid: command not found

And nothing of that will happen if you just close SSH after vesta installation - and open new one :D

Maybe it's already reported on http://bugs.vestacp.com/ - I will check it too.
And maybe it's already fixed on github, I'll check it too.

It's look like the same bug with $BIN

**Comment by serghey-rodin** [comment]
It looks good and indeed fixes some path related issues.
Thanks @SysVoid

**Pull request merged**
