### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Re-compress the png images losslessly using Google's zopflipng, 33 images optimized as below:

```
 web/images/arrow.png                                       | Bin 243 -> 97 bytes
 web/images/background-dots.png                             | Bin 173 -> 93 bytes
 web/images/document.png                                    | Bin 445 -> 380 bytes
 web/images/edit_bg.png                                     | Bin 145 -> 82 bytes
 web/images/filemanager_favicon_3.png                       | Bin 223 -> 99 bytes
 web/images/flat_icons.png                                  | Bin 13365 -> 10181 bytes
 web/images/logo.png                                        | Bin 2407 -> 1532 bytes
 web/images/pause.png                                       | Bin 157 -> 76 bytes
 web/images/sprite.png                                      | Bin 60967 -> 37382 bytes
 web/images/start.png                                       | Bin 208 -> 95 bytes
 web/images/toggle_password.png                             | Bin 311 -> 250 bytes
 web/images/ui-bg_flat_0_aaaaaa_40x100.png                  | Bin 180 -> 86 bytes
 web/images/ui-bg_glass_55_fbf9ee_1x400.png                 | Bin 120 -> 112 bytes
 web/images/ui-bg_glass_95_fef1ec_1x400.png                 | Bin 119 -> 115 bytes
 web/images/ui-icons_2e83ff_256x240.png                     | Bin 4369 -> 3686 bytes
 web/images/ui-icons_454545_256x240.png                     | Bin 4369 -> 3686 bytes
 web/images/ui-icons_888888_256x240.png                     | Bin 4369 -> 3686 bytes
 web/images/ui-icons_cd0a0a_256x240.png                     | Bin 4369 -> 3686 bytes
 web/images/unlim.png                                       | Bin 225 -> 223 bytes
 web/images/vesta_logo.png                                  | Bin 5162 -> 4075 bytes
 web/js/iviewer/img/iviewer.rotate_left.png                 | Bin 1493 -> 1400 bytes
 web/js/iviewer/img/iviewer.rotate_right.png                | Bin 1482 -> 1389 bytes
 web/js/iviewer/test/arrow.png                              | Bin 2045 -> 1632 bytes
 web/js/iviewer/test/lightbox-gallery/img/bg_transblack.png | Bin 932 -> 75 bytes
 web/js/iviewer/test/lightbox-gallery/img/btn_close.png     | Bin 1207 -> 339 bytes
 web/js/iviewer/test/lightbox-gallery/img/btn_next.png      | Bin 374 -> 223 bytes
 web/js/iviewer/test/lightbox-gallery/img/btn_prev.png      | Bin 371 -> 230 bytes
 web/js/iviewer/test/lightbox-gallery/img/btn_zoomin.png    | Bin 970 -> 103 bytes
 web/js/iviewer/test/lightbox-gallery/img/btn_zoomout.png   | Bin 959 -> 98 bytes
 web/js/iviewer/test/lightbox/img/bg_transblack.png         | Bin 932 -> 75 bytes
 web/js/iviewer/test/lightbox/img/btn_close.png             | Bin 1207 -> 339 bytes
 web/js/iviewer/test/lightbox/img/btn_zoomin.png            | Bin 970 -> 103 bytes
 web/js/iviewer/test/lightbox/img/btn_zoomout.png           | Bin 959 -> 98 bytes
```

### CODE REVIEW

**Comment by serghey-rodin** [comment]
@PeterDaveHello sounds really cool. Can you please update your PR or create new one with updated graphics?

**Comment by PeterDaveHello** [comment]
Let my try.

**Comment by PeterDaveHello** [comment]
@serghey-rodin updated.

**Comment by serghey-rodin** [comment]
@PeterDaveHello Awesome

**Pull request merged**
