### PR TITLE
Update v-update-host-certificate

### PR DESCRIPTION
**Pull request by korvinod**
Fix command in line line 75-77

### CODE REVIEW

**Comment by madeITBelgium** [comment]
I don't think this will work when you are outside of the BIN folder. Normally how it now is should work or better use the $BIN variable.

**Comment by dpeca** [comment]
This will not wo9rk, I agree with @madeITBelgium

**Comment by korvinod** [comment]
Sorry. It's really better to use $ BIN

**Comment by dpeca** [comment]
Somehow this is already implemented.

**Pull request closed without merging**
