### PR TITLE
Fix for v-change-user-package too many arguments

### PR DESCRIPTION
**Pull request by cdnmall**
v-change-user-package: line 46: [: too many arguments

### CODE REVIEW

**Comment by cdnmall** [comment]
@serghey-rodin Whats the deal @dpeca pull request get approved but everyone else with simple basic fix don't get approved or even looked at? I don't see why simple fixes like this are not approved and fix asap you don't even need to test something simple like this.  Not mention these are the bugs that need to get fixed instead of adding new features.

**Comment by dpeca** [comment]
Nobody is approving my pull requests, because I didn't made pull requests - I directly commited fix to master branch.
Before a few months core developers gave me a permission and trust to do that, so I'm fixing a bugs that I found by myself.

Anyway, I'm still new here, and I feel I should not yet decide what pull requests will be accepted - so - basically - I should not accept any pull request.

It's a Serghey's job - and he do that tipically a few days before new release comes.

So, please, be patient.

Cheers.

**Comment by dpeca** [comment]
And, by the way, I agree with this fix, this was obviously syntax error.
Thank you for fix, I'm sure it will be accepted.

**Comment by cdnmall** [comment]
Sorry I did not realize you were a collaborator I am just saying stupid errors like this should be fixed and patched immediately on github and c.vestacp.com preventing a lot of hassle for everyone down the road. As a web developer I often reload my tests servers several times a day to change os and test other stuff but when I have to make a patch script each bug it gets to be a pain which is why my installer script uses the master branch of github and pulls the other fixes i think work best from other branches but even that takes alot of time and coding.  I don't mean to sound demanding but vestacp has become a very useful tool for my online business and i would like to see the best for it. If there is something more I can do to help you guys would be happy to do it.

**Comment by dpeca** [comment]
> my installer script uses the master branch of github

Don't do that.
Currently, master branch has serious issue since this commit - https://github.com/serghey-rodin/vesta/commit/e5950d516d52fe4776c6527676d0823780a7f8d7 - you can stay with accidently deleted files due undefined variable in code.

Please use code that installer installs.

By the way, I will accept this PR, because it's obviously that you patched syntax error.

**Pull request merged**
