### PR TITLE
Add Adminer to installer

### PR DESCRIPTION
**Pull request by dreiggy**
I have added Adminer to installer. Need testing of installation.

### CODE REVIEW

**Comment by anton-reutov** [comment]
I don't think it's a safe app.

**Comment by dreiggy** [comment]
> I don't think it's a safe app.

Why you think that?

I try to check some resources and seems phpmyadmin have more historical vulnerabilities:
https://www.cvedetails.com/vendor/784/Phpmyadmin.html
https://www.cvedetails.com/vendor/17755/Adminer.html

I think Adminer should be as alternative to phpmyadmin ;) Here is comparison: https://www.adminer.org/en/phpmyadmin/

**Comment by mckaygerhard** [comment]
Adminer was superset by https://github.com/adminneo-org

this pull request must be archived as guide to implemented.. the php**admin craps are too windoze and complex to mantain

**Comment by vrana** [comment]
AdminNeo is a fork of Adminer but original Adminer is now actively developed again.

**Comment by Neustradamus** [comment]
Dear all,

@Dennis-SEG has done a very good job here:
- https://github.com/outroll/vesta/pull/2322

What do you think?

**Pull request closed without merging**
