### PR TITLE
Added api returncode header

### PR DESCRIPTION
**Pull request by chkhanu**
This way api clients will know what to expect.
Makes detecting error states a lot easier.
Backwards compatible with any existing client.

### CODE REVIEW

**Comment by chkhanu** [comment]
Any particular reason? Maybe upcoming API version?

**Comment by anton-reutov** [comment]
since the last incident with api/index.php, changes from contributors not accepted

**Comment by chkhanu** [comment]
Sorry to hear that. This  one merely adds already known integer return code via vendor-specific (X-Vesta-) header - no extra logic.

Btw, I think there is still an error in handling of the 'key' parameter in v-check-api-key script.

**Comment by anton-reutov** [comment]
@chkhanu, I send this information to Serghey Rodin and he will check it

**Pull request closed without merging**
