### PR TITLE
Deprecate GET acme v2

### LINKED ISSUE #2038: Changes in LE ACMEv2 API
### Operating System (OS/VERSION):

All systems/versions

### VestaCP Version:

0.9.8-26

### Installed Software (what you got with the installer):

apache, nginx, mysql

### Steps to Reproduce:

On November 1st, 2020 Let's Encrypt will remove support for unauthenticated GETs from the production V2 API. Since that moment, updating or creating a new certificate in VestaCP will fail because "GET" is used to download the ".pem" file (v-add-letsencrypt-domain, line 235)

### Related Issues/Forum Threads:

https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380

### PR DESCRIPTION
**Pull request by moucho**
This should fix #2038 

PS: it's from [hestiacp project](https://github.com/hestiacp/hestiacp)

### CODE REVIEW

**Comment by moucho** [comment]
I've tested it with LE staging, which does not support GET already

**Comment by dpeca** [comment]
Tested?
Is it merged in Hestia? @ScIT-Raphael 

Can someone also test this commit?
@anton-reutov @serghey-rodin

**Comment by moucho** [comment]
@dpeca 

In my private fork I have support for staging (as I said, it no longer supports GET) and generates the certificate OK. And in production also works.

In hestia this code has been there since last year (https://github.com/hestiacp/hestiacp/commit/de9c2cb5ee7927ae01408dfba594ad4e0bf2df4a)

**Comment by dpeca** [comment]
Thanks a lot, I will merge it if @serghey-rodin or @anton-reutov don't put some suggestion in next 24 hours.
Looks fine to me.

**Comment by ScIT-Raphael** [comment]
Can confirm what @moucho writes, the commit is there since a year and is working properly on every hestia system.

Do you srsly think, @serghey-rodin or @anton-reutov will write anything? Honestly, this project is dead...

**Comment by dpeca** [comment]
Many people pleased me to merge this, because they have forks that are in sync with this official repo.

**Pull request merged**
