### PR TITLE
Small code and spell check fixes for rhel installer

### PR DESCRIPTION
**Pull request by fliker09**
1) Spell check fix
2) check_error function does not exist
3) Spell check fix
4) Redundant and failing (admin user does not exist at the moment of execution). It can be found farther (and working)
5) Fix for mysql on CentOS 6 when remi is not used (this folder is mentioned on the last line of the my.cnf, which makes mysql fail on the launch when folder is not found)
6) Spell check fix

### CODE REVIEW

**Comment by dpeca** [comment]
You should send last commit in separated PR...

**Comment by fliker09** [comment]
I thought this pull request is closed considering that changes were approved... I am still working on the Amazon AMI installer

**Comment by dpeca** [comment]
''Approved'' means that I reviewed PR and said ''this is OK'' - but it is not still merged - @serghey-rodin will merge - I just helping him with code review.

**Comment by fliker09** [comment]
Sorry, my bad, not very good with github :-(

**Comment by fliker09** [comment]
Any good solutions?

**Comment by fliker09** [comment]
So, remove the file and commit or just revoke the last commit? What is the best solution?

**Comment by dpeca** [comment]
Try to remove file, then push to fliker09:master
I think that will clean this PR from additional commit.
Then push second file (that you deleted from this PR) as another PR.

**Comment by fliker09** [comment]
Decided to revert, feels more elegant :-)

**Comment by serghey-rodin** [comment]
Thanks @fliker09

**Pull request merged**
