### PR TITLE
Replace cn.php

### PR DESCRIPTION
**Pull request by myrevery**
This is the new version completely from scratch.
Huge change, more than 100% of the translated degree.
Complete and extremely accurate Chinese localization translation.
Tip: Add some new keywords to improve the quality of translation.

### CODE REVIEW

**Comment by skurudo** [comment]
+1 thanks. man

**Comment by myrevery** [comment]
@serghey-rodin
I want to be collaborators, long-term maintenance Chinese (Simplified) localization translation.

**Comment by serghey-rodin** [comment]
Thank you @myrevery. Please feel free to take patronage over Chinese translation. Can I email you when there is a gap between en and cn versions? Thanks

**Comment by myrevery** [comment]
Hello @serghey-rodin. I will explain cn and en differences.
Tip: cn.php as the goal.

1. Add keywords to correct spelling errors (Provisional through translation to correct errors)
    L178 -- "Proxy Extentions" Extentions is wrong.
    L358 -- "CDIR format is supported" CDIR is wrong.
2. New keywords
    L214 -- For server page.
    L217 -- For RRD page Apache2 Usage.
    L222-223 -- For RRD page multi-interface.
    L237-238 -- For server page service note.
    L325 -- Supplement and perfect (I'm not sure L324 is spelled wrong?)
    L389-390 -- Supplement and perfect, for BACKUP page configure restore settings.
    L504-520 -- Supplement and perfect, for Configuring Server page.
    L528-530 -- Supplement and perfect, for show: CPU / MEM / NET / DISK page.

**Pull request merged**
