### PR TITLE
Update v-update-user-quota

### PR DESCRIPTION
**Pull request by SCelik**
Quota calculation for hard limit was wrong. It must be soft + 50000 not quota + 50000

### CODE REVIEW

**Comment by skurudo** [comment]
+1

**Comment by SCelik** [comment]
Second commit is another aproach to vestas quota management. But in my opinion, best aproach must be:

Hard Quota must be equal to package value.
Soft Quota must be equal to 90% of Hard Quota, so there can be a warning when user is near the limit.
And when user uses all of package limit (real quota, hard quota) we kept our promises and user can not write any extra of bytes.

I think this is the best solution...

**Comment by skurudo** [comment]
+1

**Comment by serghey-rodin** [comment]
Good point. Thanks @SCelik

**Pull request merged**
