### PR TITLE
Corrected spelling mistakes

### PR DESCRIPTION
**Pull request by Rhyswilliamsza**
Hi Serghey,

I've corrected spelling throughout the app. This commit does not include any modifications to executing code, merely to comments and user-side messages.

Rhys

### CODE REVIEW

**Comment by SysVoid** [comment]
._.

**Comment by Rhyswilliamsza** [comment]
Hahaha sorry. Whilst digging through all the code, I thought I'd correct them before moving on to what I wanted to achieve :)

**Comment by serghey-rodin** [comment]
Incredibly great job @Rhyswilliamsza . Please give me some time to review this pull request. Thanks!

**Comment by serghey-rodin** [comment]
Thanks @Rhyswilliamsza

**Pull request merged**
