### PR TITLE
Updated Ubuntu 16.10 install script and added 17.04

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by anton-reutov** [comment]
I think that it is too early to add support for this version

**Comment by anton-reutov** [comment]
I don't see the point in supporting this version as I don't see the point in supporting 15.04

**Comment by dpeca** [comment]
We have poor support for existent 16.x, so first we need to fix it.
Anyway, this is just fix with "OR version==".... I'm not against this PR, but I feel there would need a lot of work here... neither 16.x had correct installer.
I hope I'll have some free time in future few months to fix all of it in Ubunthu installer.

**Comment by crackerizer** [comment]
I got the point. My attempt was to fix the installation script for 16.10 which supports PHP7 natively.  Adding 17.04 was before I found out that Vesta repository did not support it yet.

**Comment by anton-reutov** [comment]
@crackerizer, what is odoo ?

**Comment by crackerizer** [comment]
Sorry I forgot to mention this commit. Odoo is an open source CRM software. you can find more info about it at http://www.odoo.com

**Comment by anton-reutov** [comment]
@crackerizer, It would be better if you create a separate PR for templates

**Comment by crackerizer** [comment]
@anton-reutov, for the PR, I have stuck with this PR for quite a while. I can not open a new one. Should I close this request, reverse the commit and make a new PR again?

**Comment by anton-reutov** [comment]
@crackerizer, yes, you should make a new PRs for tempates backdrop and odoo

**Pull request closed without merging**
