### PR TITLE
Fix path to exim aliases and fwd_only files

### PR DESCRIPTION
**Pull request by Scorcher**
Checkbox "Do not store forwarded mail" doesn't work because router localuser_fwd_only has wrong path to configs.

### CODE REVIEW

**Comment by SysVoid** [comment]
good catch

**Comment by Scorcher** [comment]
Sorry... I was pushed new commit to master branch and it is merged to this pull request... :( but it is an another issue.
Reverted last one... will commit to another branch...

**Comment by Scorcher** [comment]
ref #248

**Comment by serghey-rodin** [comment]
Good catch @Scorcher I already merged this fix. Thank you

**Pull request closed without merging**
