### PR TITLE
WEB UI fix

### PR DESCRIPTION
**Pull request by ja2015**
## a small change to WEB UI.

1. Gray out 'WEB', 'DNS', 'MAIL', 'DB', 'CRON', 'BACKUP' in the header menu If they are set to '0' in the package.
2. Checkoff and disable the checkboxes 'DNS Support', 'Mail Support' in the 'ADD WEB DOMAIN' page if they are set to '0' in the package.

### CODE REVIEW

**Comment by elliot-labs** [comment]
I would love to see this implemented in the official product!

**Comment by naumov-socolov** [comment]
looks nice, I think we should hide instead of disabling checkboxes, could you do this?

**Comment by dpeca** [comment]
+1 vote for hiding.
on one server I manually delete divs that I dont need.
this will be great to make it happen automatically :)

**Comment by elliot-labs** [comment]
+1 for hiding. Currently on my client's server I just delete the html. I think auto hiding would be the best as it would be less confusing for users. I think display: none should do the trick.

Thanks!

**Comment by dpeca** [comment]
Of course, no doubt, @ja2015 - just switch it to display: none;

**Comment by ja2015** [comment]
Thanks for the comments.

I changed the code.
Menus and checkboxes are hidden by setting '0' in the package.
See the newer commit.

**Comment by elliot-labs** [comment]
Great idea on the implementation. It is much better than what I would have done :-)

**Comment by naumov-socolov** [comment]
nicely done, but there is a problem in main menu, its transparent and list content is visible through menu.
screen

**Comment by ja2015** [comment]
styles.min.css in my commit fixes the transparent problem.

**Comment by naumov-socolov** [comment]
sorry, didn't notice changes in styles.

merged, thanks @ja2015 !

**Comment by ja2015** [comment]
Thanks for merge.

**Pull request merged**
