### PR TITLE
Fix Vesta security vulnerability

### PR DESCRIPTION
**Pull request by SagePtr**
This pull request fixes multiple bugs and vulnerabilities reported here:

https://habr.com/company/ua-hosting/blog/353320/
https://forum.vestacp.com/viewtopic.php?t=16555
https://forum.vestacp.com/viewtopic.php?t=17668

Please merge this as soon as possible because it's highly critical.

### CODE REVIEW

**Comment by madeITBelgium** [comment]
seriously?

**Comment by SagePtr** [comment]
Sorry, my mistake, this fix only fixes new installation of vestaCP but doesn't fix existing installations.
For existing installations, it should print instructions how to reinstall server os (because if server uses VestaCP - it's already compromissed according to multiple reports in above forum topics).

**Comment by truongan** [comment]
Is this a joke?

**Comment by robindirksen1** [comment]
Hacktoberfest PR’s?

**Pull request closed without merging**
