### PR TITLE
Add vim-common for LetsEncrypt support

### PR DESCRIPTION
**Pull request by SysVoid**
Installation-time fix for: https://github.com/serghey-rodin/vesta/issues/735

Still need to see how to fix this for people that are updating.

### CODE REVIEW

**Comment by SysVoid** [comment]
Please don't accept the pull yet. I can't quite work out where updates are installed from.

**Comment by serghey-rodin** [comment]
Sure. Please let me know when you are ready @SysVoid

**Comment by SysVoid** [comment]
@serghey-rodin what scripts are executed when someone upgrades their Vesta installation?

**Comment by serghey-rodin** [comment]
@SysVoid it is handled by apt or rpm triggers
https://github.com/serghey-rodin/vesta/blob/master/src/deb/vesta/postinst
https://github.com/serghey-rodin/vesta/blob/master/src/rpm/specs/vesta.spec

Can you please update this PR or commit changes to the installer directly?

**Comment by serghey-rodin** [comment]
I'll close it for now. Please feel free to reopen when you are ready

**Pull request closed without merging**
