### PR TITLE
Added limit for Database User Input

### PR DESCRIPTION
**Pull request by Rhyswilliamsza**
Limits the user input of v_dbuser to 16 characters, including prefix.

### CODE REVIEW

**Comment by serghey-rodin** [comment]
@Rhyswilliamsza thanks!
@naumov-socolov can you please test this one?

**Comment by naumov-socolov** [comment]
We have that problem long time for now. And we need a complex solution.
And we already have long thread on thins issue, take a look:
https://github.com/serghey-rodin/vesta/issues/860

Sorry, but for the moment I have to decline your PR.

**Comment by Rhyswilliamsza** [comment]
No worries.

Just put it in to stop users putting in more than 16 characters into the input box, not to check server side. Just makes it more useful to name your database user, as the code wouldn't allow any more input after the 16 character limit.

Rhys

**Comment by naumov-socolov** [comment]
Postgresql have no such username limitation. 
If admin will create user with name longer then 16ch, your code will not help.

We need to have complete solution for all of cases described above.

**Comment by Rhyswilliamsza** [comment]
Aah alright!

Understood, thanks!

**Pull request closed without merging**
