### PR TITLE
Fix for issue #1286

### PR DESCRIPTION
**Pull request by lukapaunovic**
This issue #1286  is back for configurations with php-fpm.
This is the proper fix.

### CODE REVIEW

**Comment by lukapaunovic** [comment]
Will somebody already review and accept this?
This issue is ongoing on Centos 7.X

**Comment by lukapaunovic** [comment]
This bug may be fixed on ubuntu, but is still present on CentOS 7.X versions

**Comment by anton-reutov** [comment]
>This bug may be fixed on ubuntu

For debian 9 is not working.

**Comment by lukapaunovic** [comment]
@anton-reutov  what's this approving thing about?

**Comment by lukapaunovic** [comment]
I know why it's not working on debian and Ubuntu. Will open new pull.

**Comment by lukapaunovic** [comment]
I know why it's not working on debian and Ubuntu. Will open new pull.

**Comment by lukapaunovic** [comment]
New pull: https://github.com/serghey-rodin/vesta/pull/1859

**Pull request closed without merging**
