### PR TITLE
Improve email validation

### PR DESCRIPTION
**Pull request by tjebbeke**

### CODE REVIEW

**Comment by serghey-rodin** [comment]
@tjebbeke could you please replace A-Za-z0-9 with [:alnum:] regex? 
```

[root@r6 ~]# bash -x /tmp/test.sh test@ßàáâãóôþüúðäåïçèõöÿýòæéêëìíøùîûñœ.com
+ [[ ! test@ßàáâãóôþüúðäåïçèõöÿýòæéêëìíøùîûñœ.com =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,63}$ ]]
+ echo 'email address is invalid'
email address is invalid

```
http://www.francedns.co/domain/idn-domain-names.html

**Comment by tjebbeke** [comment]
@serghey-rodin done!

**Comment by serghey-rodin** [comment]
@tjebbeke perfect

**Comment by serghey-rodin** [comment]
@tjebbeke I have good news for you. You are granted access to vesta repository.
You can now commit directly to the repository if you think that your changes will not break anything.
For new features please still use PR as you used before.

Welcome a board!

**Comment by tjebbeke** [comment]
Thanks @serghey-rodin! I have seen the invitate I will accept it later this week.

**Comment by serghey-rodin** [comment]
@tjebbeke perfect1 please email me when you are ready so I can add you to dev mail list. thanks

**Pull request merged**
