### PR TITLE
dump large database fix #1251

### LINKED ISSUE #1251: mysqldump (func/db.sh) do not dealocate memory from swap
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

default installaation pack (nginx, apache, mysql, exim, dovecot, bind.

mysql version: 5.7.19

### Steps to Reproduce:

The problem related to: https://dba.stackexchange.com/a/61070
Because swap created after mysqldump usage which not cleaned from server.
Just try to use mysqldump for many different databases and you will have the same results

### Related Issues/Forum Threads:

none

### Other Notes:

Anything else?

## How to fix

1. https://github.com/serghey-rodin/vesta/blob/master/func/db.sh#L50

replace:
```
mysql_dump() {
    err="/tmp/e.mysql"
    mysqldump --defaults-file=$mycnf --single-transaction -r $1 $2 2> $err
    if [ '0' -ne "$?" ]; then
```

to 

```
mysql_dump() {
    err="/tmp/e.mysql"
    mysqldump --quick --defaults-file=$mycnf --single-transaction -r $1 $2 2> $err
    if [ '0' -ne "$?" ]; then
```

will solve the issue.

### PR DESCRIPTION
**Pull request by noogen**
Fix for issue #1251 

Also good to start working on any project with a small fix.

### CODE REVIEW

**Comment by serghey-rodin** [comment]
It's rare issue as far as I understand.
I'm going to find out how "--quick" affects import/export speed and if the time different isn't that big I'll accept this patch. Thanks for you help and keep it up :)

**Comment by Skamasle** [comment]
Hi

This option is enabled by default, because is enabled with --opt

You can read here: https://dev.mysql.com/doc/refman/5.6/en/mysqldump.html#option_mysqldump_opt

--opt: 

This option, enabled by default, is shorthand for the combination of --add-drop-table --add-locks --create-options --disable-keys --extended-insert --lock-tables --quick --set-charset. It gives a fast dump operation and produces a dump file that can be reloaded into a MySQL server quickly.

**Comment by noogen** [comment]
@Skamasle I understand and has also mentioned this in the original issue #1215, but I do not see where --opt is set.  Can you point me to where --opt is set?  I do not see it in this file: https://github.com/serghey-rodin/vesta/blob/master/func/db.sh

**Comment by Skamasle** [comment]
Hi @noogen 

This is enable by default in mysqldump, so as documentation say is enabled, so you no need put mysqldump --opt just use mysqldump 

Check link to docs, literaly say:

--opt

This option, enabled by default, is shorthand for the combination of --add-drop-table --add-locks --create-options --disable-keys --extended-insert --lock-tables --quick --set-charset. It gives a fast dump operation and produces a dump file that can be reloaded into a MySQL server quickly.

Because the --opt option is enabled by default, you only specify its converse, the --skip-opt to turn off several default settings. See the discussion of mysqldump option groups for information about selectively enabling or disabling a subset of the options affected by --opt.

**Pull request closed without merging**
