### PR TITLE
Unzip Archive overwrite fix

### PR DESCRIPTION
**Pull request by darkworks**
when zip archive is unzip it gives error  "" archive was not extracted ""  in case there were same files already present in the folder , its due to overwrite flag (-o) missing in unzip command used in vestacp

### CODE REVIEW

**Comment by makseo** [comment]
I think it is not always a good idea to overwrite the files, because it is possible to overwrite the files be mistake.
The best solution would be to create an additional checkbox in file manager extract window, where user can choose if he want to overwrite files or not.

**Comment by darkworks** [comment]
ya agree

**Comment by dpeca** [comment]
Please don't mix PR for code patching with PR for language translation update.

**Comment by darkworks** [comment]
sorry i just wanted to save the file , do not know it appear in pull request here

**Comment by darkworks** [comment]
any idea how to remove language ur.php file from it ,

**Pull request closed without merging**
