### PR TITLE
Added net2ftp file manager for apache and apache/nginx on rhel

### PR DESCRIPTION
**Pull request by mghadam**

### CODE REVIEW

**Comment by anton-reutov** [comment]
FileManager already exists in VestaCP

**Comment by mghadam** [comment]
@anton-reutov that's correct however it's not free, is it ?

**Comment by alex-connor** [comment]
@mghadam yes, this feature is not free

**Comment by joubertredrat** [comment]
Why not? is a possible free alternative.

Me for example, I host sites for free and I have high cost for this, then I don't have money for pay file manager license. Then this can be an alternative for me.

**Comment by anton-reutov** [comment]
You can install it yourself

**Comment by darkworks** [comment]
can we add it to debian .

**Comment by chipitsine** [comment]
"you can install it yourself" - is somewhat related to apache/nginx/php as well, not only net2ftp

so, in general, why use vesta if "you can install everything yourself" ?

**Comment by darkworks** [comment]
net2ftp is stable i think this pull request should be merged and support for other OS need to be added too for net2ftp .. vesta default file manager is pretty much useless , it will take years to be stable , it lack a lot of features like file editing etc 
i think they closed it because it may reduce their pro file manager plugin sales ... that's bad at should be added i guess

**Comment by darkworks** [comment]
@anton-reutov  can you re consider this pull request for merge

**Comment by anton-reutov** [comment]
> it lack a lot of features like file editing etc
What? o_O

**Comment by darkworks** [comment]
hmmm checked again live demo , ya found it , on file click it have open editor ,  good , it start when it was added i had hard time finding edit feature in it

**Pull request closed without merging**
