### PR TITLE
HTTP2 support

### PR DESCRIPTION
**Pull request by robindirksen1**
This will add a template that supports HTTP2.

Tested this with 0.9.8-17 (centos 6.4) and works fine.

### CODE REVIEW

**Comment by SysVoid** [comment]
Hi,

Please squash your commits into a single one so that we can review it in one page.

Thanks!

**Comment by robindirksen1** [comment]
Uhh, how do I do that? @SysVoid

**Comment by madeITBelgium** [comment]
@robindirksen1 Check this link: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by mgilank** [comment]
hope this will be implement soon!

**Comment by robindirksen1** [comment]
I squashed the commits, @SysVoid can you look at it?

**Comment by SysVoid** [comment]
Large PRs like this should be looked into by @serghey-rodin

**Comment by serghey-rodin** [comment]
Great job @robindirksen1

**Pull request merged**
