### PR TITLE
no need for so many servers if just for demo :)

### PR DESCRIPTION
**Pull request by cybernet**
in my opinion :)

### CODE REVIEW

**Comment by cybernet** [comment]
should i close this ?

**Comment by dpeca** [comment]
Don't close, let Serghey review this.

**Comment by serghey-rodin** [comment]
It's hard to say what fits best. I'm not really sure. @dpeca what do you think?

**Comment by dpeca** [comment]
@serghey-rodin 
I have very little expierence with php-fpm,  so I think nothing about this :D

**Pull request closed without merging**
