### PR TITLE
Release 0.9.8-16

### PR DESCRIPTION
**Pull request by myrevery**
Hello @serghey-rodin.
Update for 0.9.8-16
Complete and extremely accurate Chinese localization translation.
L591&L595&L597&L601 Core keywords need to be updated.

### CODE REVIEW

**Comment by malsony** [comment]
Oops, am I too late for the show? :laughing:

**Comment by SysVoid** [comment]
I am not sure if you're supposed to remove someone else's credits on the language files.

**Comment by serghey-rodin** [comment]
@myrevery thanks for help. Can you please sync-up with master branch in order to resolve conflicts and leave notes about original translation made by Kevin (kevin@kvm.la)

**Comment by malsony** [comment]
I have browsed the revision, and found more than 70% of contents changed from the original translation, which somehow I think, was done by a computer; the revised version by @myrevery is better for Chinese administrators.

**Comment by myrevery** [comment]
Hello @serghey-rodin. @malsony. @SysVoid.
Thanks for comment!
I think some people do not understand the difference between Simplified Chinese and Traditional Chinese.
I should point out, Kevin (kevin@kvm.la) copy most of the translation results from Traditional Chinese (tw.php), and the poor quality of translation.
And he has been for a long time did not continue updated.
So I made a complete and extremely accurate Simplified Chinese localization translation. And I will continue to update.
As early as December 2015 I submitted a better translation, but because a few core keywords conflict resulted in the repo.
So now I have to fix these errors.
In addition, I want to be Collaboration, in order to provide timely updates.

**Pull request merged**
