### PR TITLE
Correction to: #1692

### PR DESCRIPTION
**Pull request by skullwritter**
# omg this was painfull to change,
@dpeca if you have an better option i would like to know to change.
since i had time, i changed the regex to allow names like:
O'Malley
O"Malley

# Also
the names have to be escaped before use, so this is the reason for the lines:
`printf -v fname "%q\n" $5`
`printf -v lname "%q\n" $6`
or similar

### CODE REVIEW

**Comment by skullwritter** [comment]
Correction of: #1692

**Comment by Skamasle** [comment]
Can this affect security in vesta interface ?

What about PHP when parse '

**Comment by skullwritter** [comment]
@Skamasle i've put it in a way that needs the value to be escaped. so to display the value, you don't have almost any issue (i didn't try yet in the interface but i've in the cli)

**Comment by skullwritter** [comment]
@dpeca ignore this for now, i still have to correct some things (related to this PR) before moving with it.

**Comment by dpeca** [comment]
Anyhow, I never accept the things I'm not sure about :)
I leave it to Serghey and Anton to test it first...

**Comment by skullwritter** [comment]
@dpeca, the web interface does not accept correctly the settings if they have, E.G: \' or \"
i have to see that first. bot right now, i don't have time for that

**Pull request closed without merging**
