### PR TITLE
Fixing ClamAV /var/run/clamav permissions

### PR DESCRIPTION
**Pull request by dpeca**
Fixing ClamAV /var/run/clamav permissions

Reported as bug - https://bugs.vestacp.com/issues/279
Details - http://forum.vestacp.com/viewtopic.php?f=12&t=11884

### CODE REVIEW

**Comment by serghey-rodin** [comment]
@dpeca This one is no longer actual. but thanks anyway for you time and commitment

**Comment by dpeca** [comment]
Are you sure that /var/run/clamav had propper permissions after Vesta install (on Debian8) ?
Maybe Debian fixed it, however, thank you if you checked it :)

**Comment by serghey-rodin** [comment]
@dpeca I've just reopened this PR. I was sure we already applied very similar fix but let me check it again.

**Comment by dpeca** [comment]
Believe or not, I also think that I saw yesterday that there was commit that fix this issue! 
And I also said to myself ''heh, someone also fixed this'' :D
Probably we saw the same commit.
But !
Today I searched commits for vst-install-debian.sh - https://github.com/serghey-rodin/vesta/blob/master/install/vst-install-debian.sh
There is nothing about 'clam' that is related with chown or chmod.
Maybe it was commit for CentOS installer? :D

**Comment by dpeca** [comment]
That's right, centos installer :)
Found - https://github.com/serghey-rodin/vesta/commit/9873dfacd0c5df214256cc537d36755cf716a61d

**Comment by serghey-rodin** [comment]
@dpeca I have good news for you. You are granted access to vesta repository.
You can now commit directly to the repository if you fix that your changes will not break anything.
For new features please still use PR as you used before.

Please email me skid at vestacp.com

**Pull request closed without merging**
