### PR TITLE
Remove old package + Dynamic version selection (Ubuntu)

### PR DESCRIPTION
**Pull request by elliot-labs**
Removed apache2.2-common which was built for the 12.04LTS release for security reasons.
http://packages.ubuntu.com/precise/apache2.2-common
Also the latest version of Apache is in the 2.4 branch. Not the 2.2 branch.
It is now no longer needed in more recent releases of Ubuntu.

### CODE REVIEW

**Comment by SysVoid** [comment]
It might be there because we (possibly) still support 12.04.

@serghey-rodin what do you think?

**Comment by elliot-labs** [comment]
I specifically removed it only from the 16.04 installer section. Everything before 16.04 is untouched.

**Comment by elliot-labs** [comment]
I just modified the logic of which packages the installer selects. It will now select the new packages for any version of Ubuntu newer or equal to 16.04. Otherwise it will select the old packages for anything older than 16.04.

This will be extremely helpful for newer ubuntu versions as you will not need to hard code them into the installer. It will dynamically support newer versions. And if there is an exception with a new release (e.g. they remove a package or add a dependency that is required) Then we can hard code that if needed. That generally does not happen though.

**Comment by elliot-labs** [comment]
I might have messed up the logic, I did not realise that that was a string. I might not be able to do the logic on a string. crud.

**Comment by elliot-labs** [comment]
Fixed with latest commit.

**Pull request closed without merging**
