### PR TITLE
Compability for ubuntu 16.10

### PR DESCRIPTION
**Pull request by Piotr-Pht-Jasiek**
Finnaly solution for Ubuntu 16.10.

In this solution you have php5 and php7. After installation you can chose php version in nginx config file. Default php5

### CODE REVIEW

**Comment by dpeca** [comment]
Line 48
https://github.com/serghey-rodin/vesta/pull/1076/files#diff-df8da0c91e9086454c60cd468849630dR48

**Comment by Piotr-Pht-Jasiek** [comment]
Done.

**Comment by dpeca** [comment]
OK, lets now discuss this:
`echo "deb http://pl.archive.ubuntu.com/ubuntu/ vivid main restricted universe multiverse" >> /etc/apt/sources.list`
Are you absolutely sure this wont brake anything, will that just provide php5- packages?

**Comment by Piotr-Pht-Jasiek** [comment]
This is a oldest repository. In debian/ubuntu apt first check latest repository. In this case if cant find package in latest repo it try another repo's.

If it find package (for exapmle "mysql-server") in latest i oldest repo it  choose latest package.

Yes I'm absolutely sure this wont brake anything. I execute this installer version on my server.

**Comment by anton-reutov** [comment]
This line should be deleted
`#Greeting from polish hackers from S.M.S. - https://s-m-s.pl`

**Comment by dpeca** [comment]
He deleted it before I accepted push request, see comments from yesterday in this thread :)
I'm still wondering how it gets there? :)
@Piotr-Pht-Jasiek explaination? :)

**Comment by anton-reutov** [comment]
> He deleted it before I accepted push request, see comments from yesterday in this thread :)
@dpeca ok

**Pull request merged**
