### PR TITLE
Less installation steps.

### PR DESCRIPTION
**Pull request by SysVoid**
I prefer installing like this, so I assume others will.

### CODE REVIEW

**Comment by sman591** [comment]
:+1: Always good to make it easier to get started. Many other tools follow this installation pattern and it works great.

**Comment by SysVoid** [comment]
(y) Thanks @sman591

**Comment by TheLastProject** [comment]
I personally think this is a bad idea, as you're literally grabbing a "random" script of HTTP and run it without ever saving it to disk, making it very difficult to, now or later, check what code you actually ran.

**Comment by sman591** [comment]
@TheLastProject is it really random though? I think it should by all means be switched to HTTPS, but people can see the exact URL of what they're downloading and remove `| bash` if they're interested in what's being run or saving a copy for future reference

**Comment by serghey-rodin** [comment]
Thanks @SysVoid

**Pull request merged**
