### PR TITLE
Fix Dovecot Connection

### PR DESCRIPTION
**Pull request by luizjrdeveloper**
Fix dovecot Connection

### CODE REVIEW

**Comment by Neustradamus** [comment]
I confirm the solution.

Source: https://wiki.dovecot.org/Namespaces

**Comment by ioannidesalex** [comment]
@dpeca @serghey-rodin @anton-reutov can you please merge this? Submitted almost two months ago and completely ignored?

**Comment by luizjrdeveloper** [comment]
> @dpeca @serghey-rodin @anton-reutov can you please merge this? Submitted almost two months ago and completely ignored?

Simple and functional.

**Comment by dpeca** [comment]
Tested?
Why it's only for 16.04 ?

**Comment by ioannidesalex** [comment]
@dpeca I didn't test it myself. However, it has been submitted two months ago and nobody didn't take the time to open/close/request feedback on this!

I love Vesta and you know it. And I try to assist whether possible. We have been shouting and crying for months regarding the problems of Ubuntu 18.04 (one of them is Dovecot). And nobody bothered to even reply to us. And one of the problems could have been solved with a merge that has been here for two months but nobody bothered to review? That's a real shame.

**Comment by ioannidesalex** [comment]
P.S. I know that the above applies for Ubuntu 16.04, but I guess it's more than that.

**Comment by dpeca** [comment]
I'm really sorry.
As I already said in previous thread,  I maintain only Debian stuff :/
I'm not very well familiar with Ubuntu.

The other thing is that I'm very busy in my company, and I'm literally doing only necessary stuff at my office, at my life, and in this project - because I don't have a time for anything more :(
I believe the same situation is with other developers.

I know that it needs only 30 - 60 minutes to bring Ubuntu to the Virtualbox and check this issue, but then again, I always have some more important jobs to do in that moment :/

Let somebody coinfirm if this will fix issue on Ubuntu 18.04.

**Comment by ioannidesalex** [comment]
I really don't blame you for anything. Personally I don't expect/care about new features. But bugfixes is a different story. If there is no time by the team to develop/maintain this excellent project, you should let the community know. And ask for assistance. I am pretty sure many community members would be glad to assist.

**Comment by dpeca** [comment]
I asked for asistence - let somebody confirm if this will fix issue on Ubuntu 18.04.

**Comment by luizjrdeveloper** [comment]
> I asked for asistence - let somebody confirm if this will fix issue on Ubuntu 18.04.

I already tested it on Ubuntu 18.04, as it did not work I installed version 16.04, then it did not work, so I thought about debugging, I installed the problem and then installed Ubuntu 18.04 to test.

At least this namespace problem I can guarantee.
I would like to help more.
And I'm trying, as above, I figured out how to fix this problem.

**Comment by luizjrdeveloper** [comment]
> You tested that this fix works on 16.04 or 18.04 or both?

Fix only namespaces of config Dovecot to Ubuntu in both Versions.

**Comment by skullwritter** [comment]
@dpeca i use uuntu 16.04, you could ask me to test this, but i don't have the same problems as the majority of the people here, cause i fix the problems myself. the times that problems happen, i fix them and then i forgot about sharing the fixes.
the other times i share the fixes that worked for me in several systems that i have and vm's (in ubuntu 16.04)
 but you can tell me to test for Ubuntu 16.04 ;)

**Pull request merged**
