### PR TITLE
Update v-update-sys-ip

### PR DESCRIPTION
**Pull request by lukapaunovic**
vestacp.com/what-is-my-ip/ 

not working anymore, therefore replaced with ifconfig.co

### CODE REVIEW

**Comment by madeITBelgium** [comment]
vestacp.com/what-is-my-ip/ is still working here.

**Comment by dpeca** [comment]
Working from me too.

**Comment by lukapaunovic** [comment]
Well at the moment when I was using the action, it wasn't...

**Comment by anton-reutov** [comment]
Working fine

**Pull request closed without merging**
