### PR TITLE
Add GUI support for letsencrypt

### PR DESCRIPTION
**Pull request by pcfreak30**
#800

### CODE REVIEW

**Comment by SysVoid** [comment]
Code seems fine to me. Tested & working?

**Comment by pcfreak30** [comment]
It is somewhat tested, I have not ensured its full proof yet.

**Comment by SysVoid** [comment]
What's "somewhat tested"? How much have you tested it?

**Comment by pcfreak30** [comment]
I tested all of the UI and most of the backend. But never got a cert issued as I didn't have a real domain and was getting weird errors from the acme service. Was running from a docker container on centos 6. Have not had the time to try and testing on a real box.

**Comment by SysVoid** [comment]
Mail me the server IP: void@sysvoid.co
I'll point pcfreak30.sysvoid.co to it.

**Comment by pcfreak30** [comment]
Ive verified that letsencrypt is fixed on CLI permanently. The GUI has some bug fixes still.

**Comment by SysVoid** [comment]
Getting nicer. :+1:

Can't wait for this to get merged once ready.

**Comment by pcfreak30** [comment]
@SysVoid if you don't want to wait, you can checkout my fork which has all my pr's so far. https://github.com/pcfreak30/vesta/tree/reloaded

**Comment by SysVoid** [comment]
I'll wait. :)

**Comment by anton-reutov** [comment]
Hi,
Please check and test your code again
Thank you for your help

**Comment by pcfreak30** [comment]
@anton-reutov you find an issue, if so what?

**Comment by naumov-socolov** [comment]
Hi, I've tested your code at the stage of your early commits and found js errors in add web domain form, later you wrote that code is not fully tested. @anton-reutov comment is based on my tests and we would like to start final testing after you say your code is ready and fully tested. So please tell us when it is time to. Thanks for your work, we are busy at the moment working on current vesta tasks so your help is greatly appreciated. Thanks @pcfreak30!

**Comment by pcfreak30** [comment]
@naumov-socolov does my latest commit have js errors? Ive tested the ui as well and gotten no issues with it.

**Comment by naumov-socolov** [comment]
@pcfreak30 one of the firts commits had some js issues. Please let me know when you code is fully tested

**Comment by pcfreak30** [comment]
@naumov-socolov im aware of that and was long already fixed.

**Comment by naumov-socolov** [comment]
@pcfreak30 let me know when it is fully tested and ready to be merged

**Comment by pcfreak30** [comment]
@naumov-socolov someone else may need to verify as I am busy myself now on another task. If there is something wrong I am unlikely to see it anyways. The gui is also a bit of a mute point of you don't have #797 as well imho.

**Comment by pcfreak30** [comment]
It also appears I didn't add support for it to grab all the aliases from the API. If anyone wants to work on this while im not, email me and ill give access to my repo.

**Comment by DeeJaVu** [comment]
i just tested it on my domain and it just works fine

**Comment by pcfreak30** [comment]
@DeeJaVu it works but from what i can see aliases aren't added in.

**Comment by pcfreak30** [comment]
Ok I have added aliases by listing the domain in api after adding and getting the alias key.

**Comment by SysVoid** [comment]
@pcfreak30 does this work? Tested?

**Comment by pcfreak30** [comment]
@SysVoid its as tested as its going to be by me. Your welcome to test as well.

**Comment by serghey-rodin** [comment]
Ok lets do this :) 
It looks almost perfect now. I think I'll modify it a little bit after merge.
Good work @pcfreak30

**Comment by SysVoid** [comment]
:O

**Comment by anton-reutov** [comment]
**SysVoid** , what this mean?

**Comment by pcfreak30** [comment]
See #877

**Pull request merged**
