### PR TITLE
Update fa.php

### PR DESCRIPTION
**Pull request by Secretjail**

### CODE REVIEW

**Comment by Flatta** [comment]
Is there any particular reason you removed [Line 7](https://github.com/serghey-rodin/vesta/pull/967/commits/fcc841b1a3beb90c222963692c846fcdc043b81e#diff-90b98fd5f4d18eb9b5ce440152f1035fL7)?

**Comment by Secretjail** [comment]
i don't see any change / help from him.

**Comment by Flatta** [comment]
I think he did a great [work](https://github.com/serghey-rodin/vesta/commits/master?author=Ham3D).
Could you please leave the note about him?
(Sorry for my late response.)

**Comment by Secretjail** [comment]
there is just removing spaces befor array index, could you just look at line 136 at https://github.com/serghey-rodin/vesta/commit/0d39823b7c596ede4b0506ea40ea1b0c2b721d3c and there is a additional S that still there , ok if this is a great work i can remove all unwanted space in all language...
i mean he must read text line by line not just removing spaces.
so it's up to you i am pretty sure he must read all text like i did.

**Comment by Flatta** [comment]
I didn't mean to mention removing spaces, please take a look at L30-, L603-, L706-

**Comment by Secretjail** [comment]
his name added.

**Comment by Flatta** [comment]
I appreciate your improving translation,
And also thank you for your troubles!

**Pull request merged**
