### PR TITLE
public_html Permissions

### PR DESCRIPTION
**Pull request by ioannidesalex**
I believe these are the correct permissions for most famous CMS.

### CODE REVIEW

**Comment by moucho** [comment]
751 is for the root folder, but the line you suggested to change is for its contents (index.html and robots.txt) and the recommended is 644, so the owner can write and the rest only see the file (apache/nginx) , and neither can 'execute' since it's not necessary and could be dangerous if your site is infected.

**Comment by ioannidesalex** [comment]
You are right, I am sorry. However, check your error.log file and see how many permission denied you have. If you can fix it, please do.

Thank you.

**Comment by moucho** [comment]
This script sets the file permissions for a new created domain, folders and files (doesn't include any CMS)
I think in your case it has to do with the files and folders you uploaded to that folder. This script doesn't change them, it has to be done manually after uploading them.
Try to set 755 for all folders and 644 for all files (inside public_html) and it should be fixed

**Comment by ioannidesalex** [comment]
Thanks a lot.

**Pull request closed without merging**
