### PR TITLE
Update for Roundcube Password driver for Vesta

### PR DESCRIPTION
**Pull request by dpeca**
New version of roundcube 'password' plugin is expecting class instead of function.
I converted a function to class.
See http://forum.vestacp.com/viewtopic.php?f=12&t=10114&p=38666#p38630

### CODE REVIEW

**Comment by dpeca** [comment]
Explaination.

In state before patch, Roundcupe generates this error:
PHP Error: Password plugin: Broken driver vesta in /usr/share/roundcube/plugins/password/password.php on line 292 (POST /webmail/?_task=settings&_action=plugin.password-save?_task=&_action=)

If we tweak that 292. line to get more details about error, like this:
                'message' => "Password plugin: Broken driver $driver, file = $file, class = $class"

Then we will have better described error:
PHP Error: Password plugin: Broken driver vesta, file = /var/lib/roundcube/plugins/password/drivers/vesta.php, class = rcube_vesta_password in /usr/share/roundcube/plugins/password/password.php on
 line 292 (POST /webmail/?_task=settings&_action=plugin.password-save?_task=&_action=)

From this error you will see that password.php is looking for rcube_vesta_password, as I said in this pull request.

**Comment by dpeca** [comment]
I just made another commit.
That fix will allow vesta driver to comunicate with VestaCP even there is self-signed SSL cert.
Previously fsockopen failed to connect on self-signed SSL cert.

**Comment by anton-reutov** [comment]
closed #4

**Comment by serghey-rodin** [comment]
Great job! Thanks @dpeca

**Pull request merged**
