### PR TITLE
Add IDN support to is_web_domain_cert_valid

### PR DESCRIPTION
**Pull request by pcfreak30**
#1160

### CODE REVIEW

**Comment by anton-reutov** [comment]
Should be checked by Sergey Rodin

**Comment by anton-reutov** [comment]
@pcfreak30 Does this working for Lets Encrypt ?

**Comment by pcfreak30** [comment]
@anton-reutov Yes since the server I test this on heavily uses LE.

**Comment by anton-reutov** [comment]
The bugs found during the testing process
Problems with checkbox
-Checkbox for proxy support disabled by default, but nginx for domain is enabled
-Checkbox for SSL Support working is incorrectly
-Web Template APACHE2 as basedir, but in packages template for apache as "default"
-DNS records for domains is empty

Please, check and fix this issues and i will continue the test.

bugidn
bugidn2

**Comment by pcfreak30** [comment]
Really dont see how my stuff affected all that. Thinking those issues are elsewhere. But right now I don't have plans to fix theses problems. If I have a need to use vesta in the near future I may.

**Pull request closed without merging**
