### PR TITLE
nginx http2 for .stpl

### PR DESCRIPTION
**Pull request by jodumont**
Simply adding http2 in every .stpl files
which make nginx compatible with HTTP/2

### CODE REVIEW

**Comment by dpeca** [comment]
This is OK for Debian9, but on older version http2 can not be run so easily, so I think it should not be on older CentOS and Debian version.

**Comment by jodumont** [comment]
thank for you're advise;
yes we will play safe. 
so; i'll close this push and push another one with only Debian8+ Ubuntu16+ and CentOS7

**Comment by robindirksen1** [comment]
@dpeca this is for the .stpl right? In centos this is already a separate template: https://github.com/serghey-rodin/vesta/blob/master/install/rhel/7/templates/web/nginx/http2.stpl

**Comment by dpeca** [comment]
Oh, you are right.
Then again it's not necessary to alter other templates on centos7.

**Comment by robindirksen1** [comment]
Why don’t this make a default for all stpl templates?

**Comment by dpeca** [comment]
Does nginx support http2 on centos7 by default?

**Comment by dpeca** [comment]
Or it require compiling of openssl?

**Comment by robindirksen1** [comment]
I got it working with the default install of vesta, checked with https://tools.keycdn.com/http2-test and succeeded.

**Comment by dpeca** [comment]
Then OK :)

**Comment by jodumont** [comment]
@dpeca I run several CentOS7/NGINX with http/2, few with VestaCP
never compile anything

**Comment by jodumont** [comment]
o and btw this is why I was pushing for all distro
because I remark @serghey-rodin define http2 for sendy on every distro
https://github.com/serghey-rodin/vesta/blob/master/install/rhel/6/templates/web/nginx/php-fpm/sendy.stpl

**Pull request closed without merging**
