### PR TITLE
farsi/persian translation

### PR DESCRIPTION
**Pull request by skurudo**
farsi/persian translation by Foad Gh
and chinese translation

### CODE REVIEW

**Comment by ttcttctw** [comment]
I had pull requested my latest(I updated it few days ago) translation (Traditional Chinese) via GitHub already. So you don't have to merge it from your side.

**Comment by skurudo** [comment]
@ttcttctw thanks, Clark.. I was hoping it would pass a little faster

**Comment by ttcttctw** [comment]
Thank you!

**Comment by Secretjail** [comment]
thank you for this.some of stings are NOT include en.php for example when user try to restart server got message "server is going down for reboot now",so where is this ?
and i already updated my translation and i'll mail it for you again.

**Comment by skurudo** [comment]
I'll make another.

**Comment by skurudo** [comment]
https://github.com/serghey-rodin/vesta/pull/559
new pull

**Pull request closed without merging**
