### PR TITLE
fix for nginx less (apache only) installation

### PR DESCRIPTION
**Pull request by urosg80**
fixes problem with apache only installation where the certificate
challenge file is not written correctly

### CODE REVIEW

**Comment by ianklemm** [comment]
I can confirm, that this solves the issue.

**Comment by SysVoid** [comment]
Hi @urosg80. It appears that your pull request has a conflict that you must fix before I can merge this.

**Comment by urosg80** [comment]
Hi,

 

Will take a look at it later today and post an update.

 

Lep pozdrav!

 

Uroš Gaber

**Comment by SysVoid** [comment]
Thanks.

**Comment by Effectik** [comment]
Same NGINX+PHP-FPM

**Comment by NuLLFiX** [comment]
Thank you so much this worked.

https://nullfix.space

**Pull request merged**
