### PR TITLE
Create ka.php

### PR DESCRIPTION
**Pull request by devius**
Official Georgian Language file for Vesta CP
Not full but work in progress

### CODE REVIEW

**Comment by naumov-socolov** [comment]
nice work! 
I've found that some keys missing, could you please update ka.php with latest en.php file keys from github.

**Comment by anton-reutov** [comment]
Let us know when your translation will be completed
Thanks for your help

**Comment by naumov-socolov** [comment]
Could you please shorten some translations at the level when structure is not broken.
Context menus in MAIL, CRON and FILE MANAGER are way too wide and page structure is broken

file manager
cron
mail

**Comment by naumov-socolov** [comment]
@devius could you please make changes to fix menu issues, I've mentioned in previous comment:
https://github.com/serghey-rodin/vesta/pull/837#issuecomment-246650045

**Comment by devius** [comment]
I have no ability to test file manager issues, no license to use file manager ;-)
other issues will be fixed in few days

**Comment by naumov-socolov** [comment]
can you contact me (naumov.socolov gmail.com), I'll provide File Manager licence key

**Comment by devius** [comment]
I have connected you about license key, please check inbox. my email is david.machakhelidze gmaiil.com

**Comment by naumov-socolov** [comment]
nicely done, thanks @devius !

**Comment by naumov-socolov** [comment]
@devius  
I still find some problems at CRON and MAIL sections.
At MAIL it only appears when SEARCH box is focused.

mail
cron

**Pull request merged**
