### PR TITLE
Ipv6 support

### PR DESCRIPTION
**Pull request by tjebbeke**
IPV6 Support

**Problems:**
**v-add-sys-ipv6**
- IPV6ADDR_SECONDARIES
- mod_extract_forwarded
- mod_rpaf

**v-delete-sys-ipv6**
- Delete startup config

**v-delete-sys-ip**
- Delete startup config

**Netmask**
- ipv4: 255.255.255.255 (ip)
- ipv6: 64 (integer)

**Update scripts**
It’s important that the scripts run in the correct order to prevent errors.
1. upd/update_packages.sh
2. upd/add_ipv6.sh
3. upd/add_firewall_ipv6.sh

**Install Script**
In the install script, I have added some additional parameters.

–ipv4 (-4) : default ‘Yes’
–ipv6 (-6) : default ‘Yes’

**Templates**
The templates are moved to IP version directories. the default is moved to ipv4/default and copied to ipv4ipv6/default and ipv6/default and updated with ipv6 settings.

There is an upgrade script to update all the templates. (upd/update_packages.sh)

More info can you read here: http://www.tpweb.org/2016/02/10/vestacp-ipv6-support/

If there are bugs are some points that can be improved, please contact me!

### CODE REVIEW

**Comment by KeiroD** [comment]
Can you squash the commits down into as few commits as possible?

**Comment by SysVoid** [comment]
Ideally you'd want 1-5 commits.

Take a look [here](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) for instructions on how to squash.

**Comment by tjebbeke** [comment]
Done, I hope I didn't break anything by all the conflicts. I will test everything again later.

**Comment by Rubatharisan** [comment]
How is the status on this implementation?

**Comment by SysVoid** [comment]
Hey, if this is done I can merge it, so let me know.

You have to fix the conflicts first though. :+1:

**Comment by anton-reutov** [comment]
SysVoid, before merge we should testing this code

**Comment by SysVoid** [comment]
Yeah, never made it clear I tested and checked over these. :)

**Comment by SysVoid** [comment]
@tjebbeke you've got some conflicts to resolve here.

**Comment by tjebbeke** [comment]
@SysVoid Yes, I know, I currently have not engough time to fix this.

**Pull request closed without merging**
