### PR TITLE
Update nginx.conf

### PR DESCRIPTION
**Pull request by alex-connor**
Add more gzip_types
https://forum.vestacp.com/viewtopic.php?f=29&t=5100#p20750

### CODE REVIEW

**Comment by SysVoid** [comment]
https://github.com/serghey-rodin/vesta/pulls
Fix the damage you have caused, please.

**Comment by n1trux** [comment]
@alex-connor can you please fix these enormous list of senseless pull requests? It's a pain to read.

**Comment by SysVoid** [comment]
Still no fix. You should be banned from pull requests.

**Comment by skurudo** [comment]
It's mistake, I guess. Don't be so harsh please :-)

**Comment by KeiroD** [comment]
Aye, I would squash down the other pull requests into this one. Please close the other pull requests and merge those fixes into this pull request.

**Comment by SysVoid** [comment]
@skurudo my joke wasn't obvious at all. :P
Edited.

**Comment by serghey-rodin** [comment]
Good work. Thank you @alex-connor

**Pull request merged**
