### PR TITLE
Fix mistake in dkim record

### PR DESCRIPTION
**Pull request by 42p**
Fix mistake in dkim record

### CODE REVIEW

**Comment by dpeca** [comment]
why you think this code should be deleted, why it is a mistake?
please provide us more explaination.

**Comment by 42p** [comment]
https://tools.ietf.org/html/rfc6376#section-7.5

**Comment by anton-reutov** [comment]
Write more about this mistake. I cant find issues related with dkim records in our [bug tracking system](https://bugs.vestacp.com/projects/vesta-control-panel/search?utf8=%E2%9C%93&q=dkim&scope=&all_words=&all_words=1&titles_only=&issues=1&changesets=1&commit=%D0%9F%D1%80%D0%B8%D0%BD%D1%8F%D1%82%D1%8C)

**Comment by 42p** [comment]
I am not in one of the modern specifications had not seen such records. Only outdated at the moment.

**Pull request closed without merging**
