### PR TITLE
Fix: #1731

### PR DESCRIPTION
**Pull request by skullwritter**
Now checks if the domain is suspended (WEB or EMAIL or DNS) if so, continue to the next domain

### CODE REVIEW

**Comment by moucho** [comment]
Correct me if I'm wrong, but I guess if EMAIL or DNS are suspended it should attempt to renew the certificate nonetheless, because the web could be working (external DNS for example)
IMO

**Comment by skullwritter** [comment]
@moucho if dns is suspended, you cannot query the server for the name.
but i can modify if everyone wants to, i don't care, i've only put the checks to insure that the domain was fully active

**Comment by moucho** [comment]
Thinking on some examples:

- If I use Cloudflare for my domain example.com , with DNS added but  suspended on VestaCP just for the sake of it, it should renew SSL certificate.
- I may not want to use Mail support on example.com, just a website with SSL but I didn't remove support, only suspended it. Or maybe I'm going to use Zoho or GSuite, but I suspended Mail support so I can keep the mail accounts I had before migrating to one of those mail services.

IMO it should only check if the domain is active, doesn't need to check for DNS or Mail support, suspended non existant.

**Comment by skullwritter** [comment]
@moucho i'll change

**Comment by moucho** [comment]
This fix seems that has been removed on VestaCP release 24 @dpeca

**Pull request merged**
