### PR TITLE
vsftpd SSL Support & hardening

### PR DESCRIPTION
**Pull request by ioannidesalex**

### CODE REVIEW

**Comment by ioannidesalex** [comment]
FTPS Support.

**Comment by dpeca** [comment]
Tested?

**Comment by ioannidesalex** [comment]
Yes, I currently use this in production.

**Comment by ioannidesalex** [comment]
The only "caveat" is that you have to restart the FTP service when Vesta SSL is changed (the case with LetsEncrypt). However, if I am not mistaken, one recent commit that has introduced Auto update for Vesta SSL via LetsEncrypt restarts the FTP service whenever the SSL changes.

**Comment by dpeca** [comment]
Yes, here - https://github.com/serghey-rodin/vesta/commit/12306ce834f2a35ed33f2d106e97e3bf8028712a

**Comment by ioannidesalex** [comment]
So we are good. Thanks.

**Pull request merged**
