### PR TITLE
show ftp path when edit web domain

### PR DESCRIPTION
**Pull request by mix5003**

### CODE REVIEW

**Comment by serghey-rodin** [comment]
thanks a lot @mix5003 we've fixed this

**Comment by mix5003** [comment]
@serghey-rodin this still not fixed in 1.0.0-4.
Additional FTP form still not show path correctly

**Comment by anton-reutov** [comment]
**mix5003** , how i can reproduce this ?

**Comment by mix5003** [comment]
@anton-reutov edit web domain and add new Additional FTP with path 
image

**Comment by anton-reutov** [comment]
Fix will be in new hot fix release

**Pull request closed without merging**
