### PR TITLE
Fix errors when you have sub domains of the given domain.

### PR DESCRIPTION
**Pull request by tjebbeke**

### CODE REVIEW

**Comment by serghey-rodin** [comment]
Thanks @tjebbeke
I did it this way in order to validate domain aliases. With your path it will be impossible to issue certificate for domain.com and www.domain.com. isn't it?

**Comment by tjebbeke** [comment]
Oh indeed it isn't working.
When i undo my commit i have this error:
/usr/local/vesta/bin/v-check-letsencrypt-domain: line 93: $conf: ambiguous redirect
/usr/local/vesta/bin/v-check-letsencrypt-domain: line 94: $conf: ambiguous redirect
/usr/local/vesta/bin/v-check-letsencrypt-domain: line 95: $conf: ambiguous redirect
/usr/local/vesta/bin/v-check-letsencrypt-domain: line 96: $conf: ambiguous redirect
Error: Error:  Authorizations for these names not found or expired: [heremydomain].com

**Comment by serghey-rodin** [comment]
v-check-letsencrypt-domain [hereyourdomain].com
does this command return positive code?

**Comment by serghey-rodin** [comment]
Here is the fix:
```
rdomain=$(egrep "'$domain'|'$domain,|,$domain,|,$domain'" $USER_DATA/web.conf)
if [ -z "$rdomain" ]; then
    check_result $E_NOTEXIST "domain $domain doesn't exist"
fi

```
Thanks for reporting this to me @tjebbeke

**Pull request closed without merging**
