### PR TITLE
Support for Sendy with nginx

### PR DESCRIPTION
**Pull request by ioannidesalex**

### CODE REVIEW

**Comment by ioannidesalex** [comment]
Can you please add this template?

**Comment by madeITBelgium** [comment]
@ioannidesalex can you create the template also for the other OSes and versions?

**Comment by ioannidesalex** [comment]
@madeITBelgium not at this time, sorry.

**Comment by serghey-rodin** [comment]
Sorry for late response. Can you please resubmit it with stpl for ssl support? Thanks

**Comment by serghey-rodin** [comment]
I added for all supported platforms. Thanks

**Pull request closed without merging**
