### PR TITLE
Fix existing translations for Georgian Language.

### PR DESCRIPTION
**Pull request by devius**
Fix existing strings for grammar and typos.
Add new or missing strings.

### CODE REVIEW

**Review by anton-reutov — APPROVED** [review]

**Review by anton-reutov — APPROVED** [review]

**Comment by Vendetta26** [comment]
devius:master

**Comment by Vendetta26** [comment]
serghey-rodin:master

**Comment by Vendetta26** [comment]
> Fix existing strings for grammar and typos. Add new or missing strings.

**Review by Vendetta26 — COMMENTED** [review]
serghey-rodin:master

**Review by Vendetta26 — COMMENTED** [review]
gh pr checkout 2203

**Comment by anton-reutov** [comment]
**ghost**  ?

**Pull request merged**
