### PR TITLE
Fix for issue #1286

### PR DESCRIPTION
**Pull request by lukapaunovic**
Fix for issue #1286

### CODE REVIEW

**Comment by ScIT-Raphael** [comment]
@luizjr, can you please stop approve nearly every commit? there is no need to do this, jzst generate unneded notifications.

**Comment by luizjr** [comment]
> @luizjr, can you please stop approve nearly every commit? there is no need to do this, just generate useless notifications.

I am reading the commits and approved to assist in code review.
I believe you have some way to change when you do not want to be notified.

If I'm incorrect I'm sorry.

**Comment by ScIT-Raphael** [comment]
It's not only this, for example you spam also in other threads with your exim question (last two issues). By the way, just check the exim config file in /etc/exim4/exim4.conf.template, search for smarthost - this should answer your issue. I can't remove the notifications, I would like to be informed on every (important) change because we maintain a fork of vesta, called hestia.

**Comment by luizjr** [comment]
> It's not only this, for example you spam also in other threads with your exim question (last two issues). By the way, just check the exim config file in /etc/exim4/exim4.conf.template, search for smarthost - this should answer your issue. I can't remove the notifications, I would like to be informed on every (important) change because we maintain a fork of vesta, called hestia.

It's all right. I will reduce.
Anyway if it is so simple for you to solve smarthost (Exim4)
Put an example there.

**Comment by ScIT-Raphael** [comment]
Did you read what i wrote? There is a complete example inside the config file. just uncomment it and adjust the smarthost. I'm on mobile, otherwise I would point to the config line. But as I wrote, open the exim config file and search for smarthost - you will see what I mean.

**Comment by luizjr** [comment]
> Did you read what i wrote? There is a complete example inside the config file. just uncomment it and adjust the smarthost. I'm on mobile, otherwise I would point to the config line. But as I wrote, open the exim config file and search for smarthost - you will see what I mean.

With your help I have already solved my Relay question in Exim4.
Thank you.

**Comment by ScIT-Raphael** [comment]
Your welcome, sorry if you did missunderstood my request about the code approves. If you would like, checkout our fork hestiacp (just search it google), we've fixed a lot of issues and focused us to debian and ubuntu as os. If you want, please contact me under info@hestiacp.com, so we can maybe stay in contact.

**Comment by lukapaunovic** [comment]
@ScIT-Raphael  I think you are commenting on wrong pull request.

**Pull request merged**
