### PR TITLE
Safer finding VirtualHost block borders

### PR DESCRIPTION
**Pull request by dpeca**
See issue https://github.com/serghey-rodin/vesta/issues/1226

### CODE REVIEW

**Comment by dpeca** [comment]
Patch is rolled-out to my 16 production servers, so if something is wrong I'll find out it very soon.

**Comment by Skamasle** [comment]
I see than some people coment ## some lines, this code will fail if #</virtualhost> found, i suggest you add some exeptions grep -v "#</virtualhost>" or something like that this will prevent some issues if people do big modifications, not is so common but you can take in consideration

**Comment by dpeca** [comment]
But it also means that someone is also commented the begin of `<VirtualHost>` and the whole VirtualHost block, which does not make any sense...
Normal people will eventually comment somthing inside VirtualHost block, but not the boundary of it...

**Comment by noogen** [comment]
@dpeca Funny thing is that this is what I just did in my Docker to support php-fpm with nginx-apache setup: https://github.com/niiknow/vestacp/blob/master/rootfs/sysprepz/apache2-templates/php71fpm.stpl

I didn't really need the apache2 template for php-fpm so I was just creating a dummy apache2 to prevent error on the UI saying something is wrong with the template.  I guess it's back to the drawing board.

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/586

**Comment by serghey-rodin** [comment]
@dpeca I'm not sure what to do with this PR :)
Function get_web_config_lines() is ugly and I hate it.  I'm thinking about different approach. What if we will start to use separate config per domain. The only reason I didn't implement this concept from the start is fs.file-max kernel limit. But now there is another problem. I'm not sure how to convert existing configs without significant downtime.

As for your PR well it only partially solves the problem but also let administrator to get used to bad habit of modifying live configs without creating custom templates or includes.
It is a really bad habit and I was in this situation myself when I rebuild web config and website stopped to work properly only because someone added custom aliases in web conf and didn't save the in tpl or created include. Therefore I'm more inclined to reject this PR.

What do you think about one config per domain?

**Comment by dpeca** [comment]
First, I put this as PR because I'm not sure what is your thinking way about this "issue", so, no matter what, I'll agree with your decision, whatever you choose :)
Both options are ok, accepting and declining :)

I afraid you need very big refactoring for idea about one config file per domain.
And what you will get with it?
1) Ensure conf will not broken
2) People will still keep bad habits

Both stuff you also get with my PR :D 
And you avoid then big refactoring :)

BTW, I was thinking that nginx server block borders can also be measured by finding `server {` and `}` lines :D

Whatever you choose it's fine.
This PR just prevents disaster situations, nothing more, nothing less.
It does not change functionality of software.

**Comment by dpeca** [comment]
I guess it's better (for software) to find a borders by measuring it's actuall size instead of guessing it's size by watching template file.
Simply, software is smarter this way.

**Pull request closed without merging**
