### PR TITLE
Fix Gmail issue with IPv6

### PR DESCRIPTION
**Pull request by ioannidesalex**

### CODE REVIEW

**Comment by dpeca** [comment]
I vote for this, I think we should add this for all distributions.
By my expierence, GMail automaticaly marks email as SPAM if it is sent from IPv6.

**Comment by dpeca** [comment]
... even if you have correct PTR to your IPv6...

**Comment by dpeca** [comment]
@serghey-rodin will decide.
I just voted, because I had the same expirience as you.

**Comment by serghey-rodin** [comment]
I'll merge this since we do not have normal IPv6 support yet

**Comment by dpeca** [comment]
@serghey-rodin 
Do you want that I add thiss to Debian and Centos exim.conf too?

**Comment by serghey-rodin** [comment]
@dpeca  yes please and push this to all version if you can. Thank you

**Comment by dpeca** [comment]
Done - https://github.com/serghey-rodin/vesta/commit/f94e9944ecc8f0e203c926282a481a2bbc98d490

**Comment by ioannidesalex** [comment]
Thanks a lot @dpeca . Can you please check my other commits and let me know if you find anything interesting to be applied to other versions as well?

**Pull request merged**
